library(tidyverse)
library(dplyr)
library(readr)
library(Hmisc)
bmw<-read_csv("BMW_Data.csv",show_col_types = FALSE)
bmw<-separate(bmw,'model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize',c('Model','Year','Price','Transmission','Mileage','Fueltype','Tax','MPG','EngineSize'),",")
#bmw %>% ggplot(aes(Model)) + geom_histogram(stat='count')
#bmw %>% group_by(Model) %>% count() %>% arrange(desc(n))
#bmw %>% ggplot() + geom_count(mapping=aes(x=Transmission,y=Model))
bmw[,c(2:3,5,7:9)]<-sapply(bmw[,c(2:3,5,7:9)],as.numeric)
#bmw %>% group_by(Model)%>%summarise(avgprice=mean(Price)) %>% arrange(desc(avgprice))
#bmwavgprice<-bmw%>%group_by(Model)%>%mean(Price)
#bmwavgprice %>% ggplot(aes(x=Model,y=bmwavgprice)) + geom_point()
#bmw %>% ggplot(aes(x=reorder(Model,Price),y=Price))+ geom_boxplot()
bmw<-bmw %>% group_by(Model)%>%mutate(avgprice=mean(Price))%>%ungroup()
ggplot(bmw,aes(x=reorder(Model,avgprice),y=avgprice)) + geom_point()
bmw %>% group_by(Model)%>% count(Transmission) %>% arrange(Model,desc(n))
#bmwcor<-cor(bmw[,c(2,3,5,7:9)])
#bmwcortable<-as.data.frame(as.table(bmwcor))
#bmwcortable %>% filter(Freq < 1) %>% arrange(desc(Freq))
#model<-lm(Price~Year+Mileage+Model,data=bmw)
#summary(model)
#pred = data.frame(Year=2014,Mileage=100,000,Model='5 Series')
#predict(model,pred)
